on:
  workflow_dispatch:
permissions:
  id-token: write
  contents: read
jobs:
  copilot-setup-steps:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    environment: copilot
    steps:
      - name: Azure login
        uses: azure/login@a457da9ea143d694b1b9c7c869ebb04ebe844ef5
        with:
          client-id: 79fb627c-baaa-4642-8349-f4ee15ba5910
          tenant-id: 7ca3e3aa-b312-40ea-9a83-47606334634d
          subscription-id: f982324c-57e0-4f62-b58d-0edf0b53dc57
